(function(racine) {
  "use strict";
  const SOURCES = Object.freeze([
    "openagenda",
    // affiche officielle d'un événement
    "datatourisme",
    // catalogue public, licence ouverte explicite
    "structure",
    // déposée par la structure qui tient le lieu
    "autour",
    // publiée dans Autour par quelqu'un du quartier
    "site_officiel",
    // tag OSM `image` pointant le site du lieu lui-même
    "wikimedia_commons",
    // Commons, atteint par tag ou par Wikidata
    "google_places"
    // repli, affiché selon les règles Google
  ]);
  const PORTEES = Object.freeze({ LIEU: "lieu", EVENEMENT: "evenement" });
  const LARGEUR_VIGNETTE = 800;
  const LICENCES_LIBRES = /(^|[^a-z])(cc0|cc[ -]?by([ -]?sa)?([ -]?\d(\.\d)?)?|public[ -]domain|pd[ -](old|us|art)|domaine[ -]public|etalab|odbl|open[ -]data)([^a-z]|$)/i;
  const LICENCES_REFUSEES = /(fair[ -]use|non[ -]free|nc[ -]nd|by[ -]nc|tous droits|all rights reserved|copyright(ed)?\b(?![ -]free))/i;
  const MARQUES_IA = /\b(ai[ -]generated|generated by ai|ai[ -]art|midjourney|stable[ -]diffusion|dall[ -]?e|imagen|firefly|generative[ -]ai|image generee par (une )?ia|ia generative)\b/i;
  const HOTES_IA = /(^|\.)(openai|oaidalleapi[a-z0-9]*|midjourney|cdn\.midjourney|stability|replicate|leonardo\.ai|civitai)\.(com|ai|io|net|org)$/i;
  function texte(valeur) {
    return valeur == null ? "" : String(valeur);
  }
  function texteBrut(valeur) {
    return texte(valeur).replace(/<[^>]*>/g, " ").replace(/&(amp|lt|gt|quot|#39|nbsp);/g, " ").replace(/\s+/g, " ").trim();
  }
  function hote(url) {
    const m = /^https?:\/\/([^/?#]+)/i.exec(texte(url));
    return m ? m[1].toLowerCase().replace(/^www\./, "") : "";
  }
  function urlImageValide(url) {
    const u = texte(url).trim();
    if (!/^https:\/\//i.test(u)) return false;
    if (HOTES_IA.test(hote(u))) return false;
    return cheminNommeUnFichier(u);
  }
  function cheminNommeUnFichier(url) {
    const u = texte(url).trim();
    const chemin = u.replace(/^https?:\/\/[^/]+/i, "").split(/[?#]/)[0];
    const dernier = chemin.split("/").filter(Boolean).pop() || "";
    if (!dernier) return false;
    const nommeUneRessource = /\.[a-z0-9]{2,5}$/i.test(dernier) || u.indexOf("?") >= 0;
    return nommeUneRessource || !/^(main|media|images?|photos?|thumb|thumbnails?)$/i.test(dernier);
  }
  function licenceLibre(licence) {
    const l = texteBrut(licence);
    if (!l) return false;
    if (LICENCES_REFUSEES.test(l)) return false;
    return LICENCES_LIBRES.test(l);
  }
  function sentIA(...valeurs) {
    const dit = texteBrut(valeurs.filter(Boolean).join(" ")).normalize("NFD").replace(/[\u0300-\u036f]/g, "");
    return MARQUES_IA.test(dit);
  }
  function visuel(entree) {
    const e = entree || {};
    const url = texte(e.image_url || e.url).trim();
    const source = texte(e.image_source || e.source).trim();
    if (!urlImageValide(url)) return null;
    if (SOURCES.indexOf(source) < 0) return null;
    const auteur = texteBrut(e.image_author != null ? e.image_author : e.author);
    const licence = texteBrut(e.image_license != null ? e.image_license : e.license);
    const pageSource = texte(e.image_source_url || e.sourceUrl).trim();
    if (sentIA(auteur, licence, e.description, url)) return null;
    if (source === "wikimedia_commons" && !licenceLibre(licence)) return null;
    return {
      image_url: url,
      image_source: source,
      image_source_url: pageSource || "",
      image_author: auteur || "",
      image_license: licence || "",
      image_updated_at: texte(e.image_updated_at || e.updatedAt) || (/* @__PURE__ */ new Date()).toISOString(),
      image_scope: e.image_scope === PORTEES.EVENEMENT ? PORTEES.EVENEMENT : PORTEES.LIEU
    };
  }
  function creditObligatoire(v) {
    if (!v) return false;
    if (v.image_source === "google_places") return true;
    const l = texteBrut(v.image_license);
    if (/cc0|public[ -]domain|domaine[ -]public|pd[ -]/i.test(l)) return false;
    const auteur = texteBrut(v.image_author) || auteurDepuisAttribution(v.imageAttribution);
    return /cc[ -]?by/i.test(l) || !!auteur;
  }
  function depuisSourceExistante(l) {
    if (!l) return null;
    if (l.image_url && l.image_source) return visuel(l);
    const url = texte(l.image || l.image_url);
    if (!url) return null;
    const source = normaliserAncienneSource(l);
    if (!source) return null;
    if (source === "google_places") return null;
    return visuel({
      image_url: url,
      image_source: source,
      image_source_url: texte(l.image_source_url || l.url),
      image_author: l.image_author || auteurDepuisAttribution(l.imageAttribution),
      image_license: texte(l.image_license || licenceImplicite(source)),
      image_updated_at: l.image_updated_at || l.majLe || null,
      image_scope: estEvenement(l) ? PORTEES.EVENEMENT : PORTEES.LIEU
    });
  }
  function normaliserAncienneSource(l) {
    const declaree = texte(l.imageSource || l.image_source);
    if (SOURCES.indexOf(declaree) >= 0) return declaree;
    if (declaree === "datatourisme_licence") return "datatourisme";
    if (declaree === "autour_verifie") return "structure";
    const h = hote(l.image || l.image_url);
    if (/openagenda\.com$/.test(h)) return "openagenda";
    if (/wikimedia\.org$/.test(h) || /wikipedia\.org$/.test(h)) return "wikimedia_commons";
    if (/googleapis\.com$/.test(h)) return "google_places";
    if (/supabase\.(co|in)$/.test(h)) return l.verifie ? "structure" : "autour";
    const provenance = texte(l.source || (l.sources || [])[0]);
    if (provenance === "openagenda" || provenance === "datatourisme") return provenance;
    if (provenance === "autour") return l.verifie ? "structure" : "autour";
    return "";
  }
  function licenceImplicite(source) {
    if (source === "openagenda") return "affiche fournie par l\u2019organisateur";
    if (source === "datatourisme") return "licence ouverte (catalogue DATAtourisme)";
    if (source === "structure") return "fournie par la structure";
    if (source === "autour") return "publi\xE9e dans Autour";
    if (source === "site_officiel") return "site officiel du lieu";
    if (source === "google_places") return "Google Places (attribution requise)";
    return "";
  }
  function auteurDepuisAttribution(brut) {
    if (!brut) return "";
    if (typeof brut === "string") return brut;
    const liste = Array.isArray(brut) ? brut : [brut];
    return liste.map((a) => texteBrut(a && a.name)).filter(Boolean).join(", ");
  }
  function estEvenement(l) {
    return !!(l && (l.isTemporary || l.debutLe || l.debut_le || l.start_at));
  }
  const TAGS_INTERDITS = Object.freeze([
    "brand:wikidata",
    "operator:wikidata",
    "subject:wikidata",
    "architect:wikidata",
    "artist:wikidata",
    "network:wikidata",
    "brand:wikipedia",
    "operator:wikipedia"
  ]);
  function tagsDuLieu(l) {
    const t = l && l.tags || {};
    return t && typeof t === "object" ? t : {};
  }
  function depuisTagsOsm(l) {
    const t = tagsDuLieu(l);
    const commons = texte(t.wikimedia_commons).trim();
    const wikidata = texte(t.wikidata).trim();
    return {
      /* `image=*` est une URL libre : elle n'est retenue que si on peut dire
         de qui elle est (voir `imageOsmAutorisee`). */
      image: texte(t.image).trim(),
      commons: /^(File|Fichier|Category|Catégorie):/i.test(commons) ? commons : "",
      wikidata: /^Q\d+$/.test(wikidata) ? wikidata : ""
    };
  }
  function imageOsmAutorisee(l) {
    const t = tagsDuLieu(l);
    const url = texte(t.image).trim();
    if (!urlImageValide(url)) return null;
    const h = hote(url);
    if (/wikimedia\.org$/.test(h) || /wikipedia\.org$/.test(h)) return { commons: fichierCommonsDepuisUrl(url) };
    const officiels = [t.website, t["contact:website"], l && l.url].map((u) => hote(u)).filter(Boolean);
    if (officiels.indexOf(h) < 0) return null;
    return {
      visuel: visuel({
        image_url: url,
        image_source: "site_officiel",
        image_source_url: texte(t.website || t["contact:website"] || l && l.url),
        image_author: texte(l && (l.titre || l.title)),
        image_license: licenceImplicite("site_officiel")
      })
    };
  }
  function fichierCommonsDepuisUrl(url) {
    const m = /\/(?:commons\/)?(?:thumb\/)?[0-9a-f]\/[0-9a-f]{2}\/([^/?#]+)/i.exec(texte(url)) || /Special:FilePath\/([^/?#]+)/i.exec(texte(url)) || /\/wiki\/(?:File|Fichier):([^/?#]+)/i.exec(texte(url));
    return m ? "File:" + decodeURIComponent(m[1]) : "";
  }
  const COMMONS_API = "https://commons.wikimedia.org/w/api.php";
  const WIKIDATA_API = "https://www.wikidata.org/w/api.php";
  function urlApiCommons(titre) {
    return COMMONS_API + "?action=query&format=json&origin=*&formatversion=2&prop=imageinfo&iiprop=url%7Cextmetadata%7Ctimestamp&iiextmetadatafilter=" + encodeURIComponent("Artist|LicenseShortName|License|Credit|ImageDescription|Categories|DateTime") + "&iiurlwidth=" + LARGEUR_VIGNETTE + "&titles=" + encodeURIComponent(titre);
  }
  function urlApiCommonsCategorie(categorie) {
    return COMMONS_API + "?action=query&format=json&origin=*&formatversion=2&list=categorymembers&cmtype=file&cmsort=sortkey&cmlimit=8&cmtitle=" + encodeURIComponent(categorie);
  }
  function urlApiWikidata(qid) {
    return WIKIDATA_API + "?action=wbgetclaims&format=json&origin=*&property=P18&entity=" + encodeURIComponent(qid);
  }
  function pageCommons(titre) {
    return "https://commons.wikimedia.org/wiki/" + encodeURIComponent(texte(titre).replace(/ /g, "_"));
  }
  function lireCommons(charge, titre) {
    const pages = charge && charge.query && charge.query.pages;
    const page = Array.isArray(pages) ? pages[0] : pages && typeof pages === "object" ? Object.values(pages)[0] : null;
    const info = page && Array.isArray(page.imageinfo) ? page.imageinfo[0] : null;
    if (!info) return null;
    const meta = info.extmetadata || {};
    const champ = (nom) => texteBrut(meta[nom] && meta[nom].value);
    return visuel({
      image_url: texte(info.thumburl || info.url),
      image_source: "wikimedia_commons",
      image_source_url: texte(info.descriptionurl) || pageCommons(titre || page && page.title),
      image_author: champ("Artist") || champ("Credit"),
      image_license: champ("LicenseShortName") || champ("License"),
      image_updated_at: texte(info.timestamp) || null,
      description: [champ("ImageDescription"), champ("Categories"), champ("Credit")].join(" ")
    });
  }
  function lireCategorieCommons(charge) {
    const membres = charge && charge.query && charge.query.categorymembers;
    if (!Array.isArray(membres)) return "";
    const fichier = membres.map((m) => texte(m && m.title)).find((titre) => /^(File|Fichier):/i.test(titre) && /\.(jpe?g|png|webp)$/i.test(titre));
    return fichier || "";
  }
  function lireWikidata(charge) {
    const revendications = charge && charge.claims && charge.claims.P18;
    if (!Array.isArray(revendications) || !revendications.length) return "";
    const valeur = revendications[0] && revendications[0].mainsnak && revendications[0].mainsnak.datavalue && revendications[0].mainsnak.datavalue.value;
    const nom = texte(valeur).trim();
    return nom ? "File:" + nom : "";
  }
  function depuisPhotoAutour(l) {
    if (!l) return null;
    const photo = (Array.isArray(l.photosAutour) ? l.photosAutour : []).find((p) => p && urlImageValide(p.url));
    if (!photo) return null;
    return visuel({
      image_url: photo.url,
      image_source: photo.verifie ? "structure" : "autour",
      image_source_url: texte(photo.pageUrl || l.url),
      image_author: texte(photo.auteur || l.creatorName || l.par),
      image_license: licenceImplicite(photo.verifie ? "structure" : "autour"),
      image_updated_at: photo.depuis || null
    });
  }
  function depuisGoogle(l) {
    if (!l) return null;
    const photos = (Array.isArray(l.photosGoogle) ? l.photosGoogle : []).slice();
    if (normaliserAncienneSource(l) === "google_places" && texte(l.image)) {
      photos.push({ url: texte(l.image), attribution: l.imageAttribution });
    }
    const photo = photos.find((p) => p && urlImageValide(p.url));
    if (!photo) return null;
    return visuel({
      image_url: photo.url,
      image_source: "google_places",
      image_source_url: l.idGoogle ? "https://www.google.com/maps/place/?q=place_id:" + encodeURIComponent(l.idGoogle) : "",
      image_author: auteurDepuisAttribution(photo.attribution),
      image_license: licenceImplicite("google_places")
    });
  }
  function persistable(v) {
    return !!v && v.image_source !== "google_places";
  }
  const MAX_CANDIDATS = 8;
  const MAX_SIMULTANEES = 3;
  const DELAI_MS = 8e3;
  const memoire = /* @__PURE__ */ new Map();
  const enVol = /* @__PURE__ */ new Map();
  let sorties = 0;
  function cle(l) {
    if (!l) return "";
    if (l.autourId) return String(l.autourId);
    if (l.id) return String(l.id);
    const nom = texte(l.titre || l.title).toLowerCase();
    const y = Number(l.lat), x = Number(l.lng);
    if (!nom || !Number.isFinite(y) || !Number.isFinite(x)) return "";
    return nom + "@" + y.toFixed(4) + "," + x.toFixed(4);
  }
  async function json(url, options) {
    const o = options || {};
    const chercher = o.fetch || racine.fetch;
    if (typeof chercher !== "function") return null;
    try {
      const r = await chercher(url, {
        signal: o.signal || (typeof AbortSignal !== "undefined" && AbortSignal.timeout ? AbortSignal.timeout(o.delai || DELAI_MS) : void 0),
        headers: { accept: "application/json" }
      });
      if (!r || !r.ok) return null;
      return await r.json();
    } catch (e) {
      return null;
    }
  }
  async function resoudreCommons(titre, options) {
    let fichier = texte(titre).trim();
    if (!fichier) return null;
    if (/^(Category|Catégorie):/i.test(fichier)) {
      fichier = lireCategorieCommons(await json(urlApiCommonsCategorie(fichier), options));
      if (!fichier) return null;
    }
    return lireCommons(await json(urlApiCommons(fichier), options), fichier);
  }
  async function resoudreWikidata(qid, options) {
    const fichier = lireWikidata(await json(urlApiWikidata(qid), options));
    return fichier ? resoudreCommons(fichier, options) : null;
  }
  async function resoudre(lieu, options) {
    const o = options || {};
    const k = cle(lieu);
    if (k && memoire.has(k)) return memoire.get(k);
    if (k && enVol.has(k)) return enVol.get(k);
    const travail = (async () => {
      const existante = depuisSourceExistante(lieu);
      if (existante) return existante;
      const tags = depuisTagsOsm(lieu);
      const osmImage = imageOsmAutorisee(lieu);
      if (osmImage && osmImage.visuel) return osmImage.visuel;
      const candidatsCommons = [];
      if (osmImage && osmImage.commons) candidatsCommons.push(osmImage.commons);
      if (tags.commons) candidatsCommons.push(tags.commons);
      for (const titre of candidatsCommons) {
        const v = await resoudreCommons(titre, o);
        if (v) return v;
      }
      if (tags.wikidata) {
        const v = await resoudreWikidata(tags.wikidata, o);
        if (v) return v;
      }
      const autour = depuisPhotoAutour(lieu);
      if (autour) return autour;
      if (o.google !== false) {
        const g = depuisGoogle(lieu);
        if (g) return g;
      }
      return null;
    })();
    if (k) enVol.set(k, travail);
    try {
      const v = await travail;
      if (k) memoire.set(k, v);
      return v;
    } finally {
      if (k) enVol.delete(k);
    }
  }
  async function resoudreLot(lieux, options) {
    const o = options || {};
    const liste = (Array.isArray(lieux) ? lieux : []).slice(0, o.max || MAX_CANDIDATS);
    const file = liste.slice();
    const trouves = [];
    async function ouvrier() {
      for (; ; ) {
        const l = file.shift();
        if (!l) return;
        if (sorties >= MAX_SIMULTANEES) {
          file.unshift(l);
          return;
        }
        sorties += 1;
        try {
          const v = await resoudre(l, o);
          if (v) {
            trouves.push({ lieu: l, visuel: v });
            if (appliquer(l, v) && typeof o.redessiner === "function") o.redessiner();
          }
        } finally {
          sorties -= 1;
        }
      }
    }
    await Promise.all(Array.from({ length: Math.min(MAX_SIMULTANEES, file.length) }, ouvrier));
    return trouves;
  }
  function appliquer(lieu, v) {
    if (!lieu || !v) return false;
    if (lieu.image && lieu.image_scope === PORTEES.EVENEMENT && v.image_scope !== PORTEES.EVENEMENT) return false;
    if (lieu.image === v.image_url && lieu.image_source === v.image_source) return false;
    lieu.image_url = v.image_url;
    lieu.image_source = v.image_source;
    lieu.image_source_url = v.image_source_url;
    lieu.image_author = v.image_author;
    lieu.image_license = v.image_license;
    lieu.image_updated_at = v.image_updated_at;
    lieu.image_scope = v.image_scope;
    lieu.image = v.image_url;
    lieu.imageSource = v.image_source;
    lieu.imageAttribution = creditObligatoire(v) && v.image_author ? [{ name: v.image_author, url: v.image_source_url }] : null;
    return true;
  }
  function oublier() {
    memoire.clear();
    enVol.clear();
    sorties = 0;
  }
  racine.AutourImages = {
    SOURCES,
    PORTEES,
    LARGEUR_VIGNETTE,
    MAX_CANDIDATS,
    MAX_SIMULTANEES,
    TAGS_INTERDITS,
    /* décisions pures — éprouvables sans réseau */
    urlImageValide,
    licenceLibre,
    sentIA,
    visuel,
    creditObligatoire,
    persistable,
    depuisSourceExistante,
    normaliserAncienneSource,
    depuisTagsOsm,
    imageOsmAutorisee,
    depuisPhotoAutour,
    depuisGoogle,
    fichierCommonsDepuisUrl,
    licenceImplicite,
    lireCommons,
    lireCategorieCommons,
    lireWikidata,
    urlApiCommons,
    urlApiCommonsCategorie,
    urlApiWikidata,
    pageCommons,
    /* enchaînement */
    cle,
    resoudre,
    resoudreLot,
    resoudreCommons,
    resoudreWikidata,
    appliquer,
    _oublier: oublier,
    _etat: () => ({ memoire: memoire.size, enVol: enVol.size, sorties })
  };
})(typeof window !== "undefined" ? window : globalThis);
